<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-00F8VL6" failures="1" tests="5" name="Listener Testcase" time="0.136" errors="0" timestamp="20 Sep 2024 12:46:55 GMT">
  <testcase classname="com.testNG.listeners.SampleTestClass" name="testFour" time="0.02">
    <skipped/>
  </testcase> <!-- testFour -->
  <testcase classname="com.testNG.listeners.SampleTestClass" name="testGetData" time="0.004"/>
  <testcase classname="com.testNG.listeners.SampleTestClass" name="testGetData" time="0.007"/>
  <testcase classname="com.testNG.listeners.SampleTestClass" name="testOne" time="0.003"/>
  <testcase classname="com.testNG.listeners.SampleTestClass" name="testThree" time="0.015">
    <failure type="java.lang.AssertionError" message="expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [5]
at com.testNG.listeners.SampleTestClass.testThree(SampleTestClass.java:30)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testThree -->
</testsuite> <!-- Listener Testcase -->
